version: "3"
services:
  web:
    image: bpringe/shared-canvas:alpha
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet: